name: ceppe-promo
channels:
- conda-forge
- anaconda-fusion
- defaults
dependencies:
- ipython=6.1.0=py36_0
- ipywidgets=7.0.0=py36_1
- jupyter=1.0.0=py36_0
- matplotlib=2.0.2=py36_2
- numpy=1.13.1=py36_blas_openblas_200
- pandas=0.20.3=py36_1
- python=3.6.2=0
- scipy=0.19.1=py36_blas_openblas_202
- sympy=1.1.1=py36_0

